apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "vlei-server.fullname" . }}
  annotations:
    rollme: {{ randAlphaNum 5 | quote }}
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
